name: Deploy to Salesforce

on:
  push:
    branches:
      - main  # change this if you want a different branch to trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate with JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SF_USERNAME }} --instanceurl ${{ secrets.SF_INSTANCE_URL }} --setalias ${{ secrets.SF_ALIAS }}

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app -u ${{ secrets.SF_ALIAS }} --json
