name: Deploy to Salesforce

on:
  push:
    branches:
      - main  # change this if you want a different branch to trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI (sf)
        run: |
          npm install @salesforce/cli --global

      - name: Authenticate with Salesforce using JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --alias ${{ secrets.SF_ALIAS }} \
            --set-default

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --source-dir force-app --target-org ${{ secrets.SF_ALIAS }} --json
